# Generated by Django 4.2.7 on 2023-12-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0004_shipment_store_shipment_store_shipment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
