# Generated by Django 4.2.7 on 2023-12-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0006_alter_shipment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.IntegerField(),
        ),
    ]
