# Generated by Django 4.2.7 on 2023-12-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0007_alter_inventory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.FloatField(),
        ),
    ]
